import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("installed plugin exposes persistent progress for model and clustering flows", async () => {
  const settings = await readFile(new URL("../src/settings.ts", import.meta.url), "utf8");
  const main = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  const progress = await readFile(new URL("../src/progress.ts", import.meta.url), "utf8");
  const embedding = await readFile(new URL("../src/embedding.ts", import.meta.url), "utf8");
  const css = await readFile(new URL("../styles.css", import.meta.url), "utf8");
  assert.match(settings, /<progress|createEl\("progress"/);
  assert.match(settings, /setBusy\(true\)/);
  assert.match(settings, /Download failed/);
  assert.match(main, /new AtomicClustersProgress/);
  assert.match(main, /cache scan/);
  assert.match(main, /EmbeddingLogStore/);
  assert.match(main, /freshEmbeddingFailed/);
  assert.match(main, /status: embeddingError \? "failed" : "completed"/);
  assert.match(main, /stage: "clustering"/);
  assert.match(main, /open-embedding-log/);
  assert.match(main, /shell\.openPath/);
  assert.match(main, /getBasePath/);
  assert.match(main, /embedding-log\.json/);
  assert.match(main, /No embedding log is available yet/);
  assert.match(main, /Could not open embedding log/);
  assert.match(main, /readBinary/);
  assert.match(main, /createObjectURL/);
  assert.match(main, /prepareLocalOrtRendererModule/);
  assert.match(main, /disposeLocalOrtAssets/);
  assert.match(main, /current = \(current as \{ cause\?: unknown \}\)\?\.cause/);
  assert.match(embedding, /wasmBinary/);
  assert.match(embedding, /webgpuMjs/);
  assert.match(embedding, /yieldToEventLoop/);
  assert.doesNotMatch(main, /class EmbeddingLogModal/);
  assert.doesNotMatch(main, /atomic-clusters-log-table/);
  assert.match(settings, /Open embedding log/);
  assert.match(settings, /ClusterRunControls/);
  assert.match(settings, /Build clusters/);
  assert.match(settings, /isRunning\(\)/);
  assert.match(settings, /persistent progress Notice/);
  assert.match(main, /build: \(\) => this\.buildClusters\(\)/);
  assert.match(main, /cancel: \(\) => this\.cancelClustering\(\)/);
  assert.match(main, /runAbortController/);
  assert.match(main, /runSignal/);
  assert.match(main, /\.abort\(\)/);
  assert.match(main, /Clustering cancelled/);
  assert.match(progress, /new Notice\("", 0\)/);
  assert.match(progress, /setTimeout\(\(\) => this\.hide/);
  assert.match(css, /atomic-clusters-progress-notice/);
});

test("embedding log contract contains diagnostics but no payload fields", async () => {
  const settings = await readFile(new URL("../src/settings.ts", import.meta.url), "utf8");
  const types = await readFile(new URL("../src/types.ts", import.meta.url), "utf8");
  const storage = await readFile(new URL("../src/storage.ts", import.meta.url), "utf8");
  const main = await readFile(new URL("../src/main.ts", import.meta.url), "utf8");
  assert.match(types, /EmbeddingLogEntry/);
  assert.match(types, /durationMs/);
  assert.match(types, /error\?: string/);
  assert.match(storage, /embedding-log\.json/);
  assert.match(storage, /async load\(\): Promise<EmbeddingRunLog \| null>/);
  assert.match(types, /status\?: "completed" \| "failed" \| "cancelled"/);
  assert.match(types, /stage\?: "preflight" \| "embedding" \| "clustering"/);
  assert.match(settings, /Test local runtime/);
  assert.match(settings, /Auto \(WebGPU → WASM CPU\)/);
  assert.match(types, /LocalExecutionProvider/);
  assert.match(settings, /runtime \$\{update\.phase\}/);
  assert.match(main, /provider\.preflight/);
  assert.match(main, /stage: "preflight"/);
  assert.match(main, /progress: 0\.25 \+/);
  assert.match(main, /progress: 0\.84 \+/);
  assert.match(types, /error\?: string/);
  assert.doesNotMatch(main, /entry\.content|entry\.vector/);
  assert.doesNotMatch(main, /EmbeddingLogModal|atomic-clusters-log-table/);
  assert.doesNotMatch(types, /content:\s*string.*EmbeddingLogEntry/);
  assert.doesNotMatch(types, /vector:\s*number\[\].*EmbeddingLogEntry/);
});
